### PR TITLE
Support to access the server property

### PR DESCRIPTION
**Pull request by johnjelinek**

### CODE REVIEW

**Comment by johnjelinek** [comment]
Trying #4 again

**Comment by johnjelinek** [comment]
I'm not sure if the type of `server` should be something like the node http server instead, since `http-server` unions with it.

**Comment by unional** [comment]
What's the benefit of accessing the server property? I don't know if it should be public or not.
If it does, then yes, it should not be of type `HttpServer`. Need to typed `union` and use its typings

**Comment by johnjelinek** [comment]
@unional: example usage:

```
import * as hs from "http-server";
import chokidar = require("chokidar-socket-emitter");
let server = hs.createServer(<hs.Option>{
    root: process.cwd()
});
chokidar({
    app: server.server,
    relativeTo: process.cwd(),
    dir: process.cwd(),
    path: process.cwd()
});
```

The server has all of the properties of a node `http` server.

**Comment by unional** [comment]
I would suggest to put it as `server: any` for now until `union` is typed (are you interested in doing so? 😄 ).

**Comment by johnjelinek** [comment]
`any` will do :)

**Comment by johnjelinek** [comment]
after this is accepted, how do I updated my references to `HEAD` of this repo? I tried `typings i --dev http-server` and it didn't get latest.

**Comment by unional** [comment]
Once this is merged:
https://github.com/typings/registry/pull/502

Then you can `typings i http-server`

**Pull request merged**
