### PR TITLE
Support to listen on an optional port number

### PR DESCRIPTION
**Pull request by johnjelinek**

### CODE REVIEW

**Comment by unional** [comment]
Thx

**Comment by johnjelinek** [comment]
@unional: quick question -- how do I update my `typings` references to include this change?

**Comment by unional** [comment]
I was waiting for your other PR to go through so I can update them together.

essentially need to update the commitish in `typings/registry/npm/http-server.json`

**Comment by johnjelinek** [comment]
oic, I thought `typings` was supposed to be decentralized-ish, so I assumed the registry would track latest.

**Comment by unional** [comment]
It's decentrialized in a sense that the actual typings are managed in separate repo such as this one.

**Pull request merged**
